swagger: '2.0'
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: applied-skills-project-5ygjeqjcuq-lm.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://applied-skills-project-5ygjeqjcuq-lm.a.run.app
  protocol: h2
paths:
  /api/messages:
    get:
      operationId: get-messages
      summary: Get messages
      responses:
        '200':
          description: A successful response
          schema:
            type: array
            items:
              type: string
    post:
      operationId: post-message
      summary: Post message
      parameters:
        - in: body
          name: message
          description: The message to create.
          schema:
            type: object
            properties:
              message:
                type: string
                example: Test message
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /api/messages/{id}:
    get:
      operationId: get-message
      summary: Get message
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: id of message to get
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    delete:
      operationId: delete-message
      summary: Delete message
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: id of message to get
      responses:
        '200':
          description: A successful response
          schema:
            type: string